In [4]:
import numpy as np

In [5]:
print(np.log(np.exp(5.2)))
print(np.cos(np.pi))
print(np.sqrt(1.21))

5.2
-1.0
1.1


In [11]:
array=np.array([1,2,3])
print(array)

matrix = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(matrix)
print(np.transpose(matrix))
print(matrix.T)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [46]:
array2=np.arange(0,20)
print(array2)
array3=np.arange(0,20,4)
print(array3)
array4=np.linspace(6,18,3)
print(array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  4  8 12 16]
[  6.  12.  18.]


In [26]:
print(array2.reshape(5,4))
print(np.zeros([5,4]))
print(np.ones([5,4]))
#5*5 identity matrix
print(np.eye(5))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [34]:
#matrix multiplication
matrix5by5 = np.arange(0,20).reshape(5,4)
matrix5by5_2 = np.arange(20,40).reshape(4,5)
product = np.matmul(matrix5by5,matrix5by5_2)
print(product)
#print(np.linalg.solve(matrix5by5,product))


[[ 190  196  202  208  214]
 [ 630  652  674  696  718]
 [1070 1108 1146 1184 1222]
 [1510 1564 1618 1672 1726]
 [1950 2020 2090 2160 2230]]


In [47]:
matrixrandom = np.random.rand(4,4)
#uniform random variable from 0 to 1
print(matrixrandom)

#standard random matrix mean zero variance 1
matrixrandomn = np.random.randn(4,4)
print(matrixrandomn)
print(np.mean(matrixrandomn))
print(np.std(matrixrandomn))
print(np.mean(matrixrandomn))
print(np.max(matrixrandomn))

[[ 0.24124676  0.39315023  0.59947643  0.71386888]
 [ 0.27493241  0.51339805  0.55164542  0.98031676]
 [ 0.82931883  0.66085705  0.77093374  0.75092704]
 [ 0.8615711   0.82603268  0.6904396   0.03951685]]
[[-0.40565811  1.36401632  0.47429195 -0.26354613]
 [ 0.68737963  0.78018123 -1.29851774  0.3007676 ]
 [-1.03337847 -1.12070026 -0.65721357  0.36493139]
 [-0.55825252  0.7916202   0.8091892   1.05446662]]
0.0805985840684
0.816520570343
0.0805985840684
1.36401632069


In [58]:
#How to access vector members in numpy array
numpyarr=np.random.randn(20)
print(numpyarr)
print(numpyarr[9])
print(numpyarr[6:12])
print(numpyarr>0)
print(numpyarr[numpyarr>0])

[ 0.91678147  0.33661036 -0.31108679 -0.07978864  0.45962425 -0.36384215
  0.18225441  0.62566071 -0.69294424  0.42379215 -0.50464164  0.35106318
 -0.76104346  0.2993386  -0.24413045  0.78413354 -1.01261365  0.2505791
  0.76725224 -0.01830819]
0.423792147276
[ 0.18225441  0.62566071 -0.69294424  0.42379215 -0.50464164  0.35106318]
[ True  True False False  True False  True  True False  True False  True
 False  True False  True False  True  True False]
[ 0.91678147  0.33661036  0.45962425  0.18225441  0.62566071  0.42379215
  0.35106318  0.2993386   0.78413354  0.2505791   0.76725224]
